386_OBJECTS= \
    $(_OBJ_DIR)\i386\myfault.res \
    $(_OBJ_DIR)\i386\myfault.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\myfault.res \
    $(_OBJ_DIR)\ia64\myfault.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\myfault.res \
    $(_OBJ_DIR)\amd64\myfault.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\myfault.res \
    $(_OBJ_DIR)\arm\myfault.obj

PASS0_ARM_OBJECTS=

